name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    # needs: test
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "ec2-3-144-236-159.us-east-2.compute.amazonaws.com"  
          REMOTE_USER: "ec2-user"
          TARGET: "/home/ec2-user/express-app"

